#!/bin/bash

if [ "$1" == "start" ] || [ "$1" == "-s" ]
then
    sudo chmod 777 /opt/seraph_esh/start.sh
    /opt/seraph_esh/start.sh
elif [ "$1" == "stop" ] || [ "$1" == "-k" ]
then
    sudo chmod 777 /opt/seraph_esh/stop.sh
    /opt/seraph_esh/stop.sh
elif [ "$1" == "restart" ] || [ "$1" == "-r" ]
then
    sudo chmod 777 /opt/seraph_esh/restart.sh
    /opt/seraph_esh/restart.sh
elif [ "$1" == "update" ] || [ "$1" == "-u" ]
then
    sudo chmod 777 /opt/seraph_esh/update.sh
    /opt/seraph_esh/update.sh
elif [ "$1" == "debug" ] || [ "$1" == "-d" ]
then
    sudo pm2 logs --raw
elif [ "$1" == "version" ] || [ "$1" == "-v" ]
then
    echo ""
    cat /opt/seraph_esh/version
    echo ""
else
    echo ""
fi
